### ISSUE TITLE
Global Implementation

### ISSUE THREAD

**Issue by joeyoropesa-dev** [5ec1cff/TrickyStore#51] opened 2024-08-19 07:12 UTC
Global Implementation works in the way that if user instead of targeting specific list of app it can choose to target all of them.

User just need to remove all packages from target.txt and to put word "all". That will enable global implementation

The only thing that needs to be done is that in service AndroidManifest.xml, specific permission is required to be able to access the list of all packages in the system (of course, if root access already grant this permission by default): 

`<uses-permission android:name="android.permission.QUERY_ALL_PACKAGES" />
`

Of course this implementation needs improvements but it's really a great idea to start from some base. Also, I would recommend in future improvements for better stability of this implementation to get blacklist.txt support that will be used when global feature is being used. For example, specific set of packages will not be spoofed that are in the blacklist.txt - they will be skipped even if they were found during package listing in config.kt

And also, adding ability for service to get restarted as soon an new package got installed/removed would be also recommended to be able to apply changes in-real-time without requiring user to reboot.

And also some additional improvements to handle "!" and "?" prefix

Thanks in advance for the dev that made this tweak possible and this feature will also improve user experience and more automated processes.

Path to the file with changes: [/master/service/src/main/java/io/github/a13e300/tricky_store/Config.kt](https://github.com/admin-elvistrujanovic/TrickyStore/blob/master/service/src/main/java/io/github/a13e300/tricky_store/Config.kt)

**Comment by joeyoropesa-dev** [comment] 2024-08-19 07:16
@5ec1cff Could you kindly check the code with changes? Thanks.

**Comment by joeyoropesa-dev** [comment] 2024-08-20 11:52
@5ec1cff Is there an reason why you closed Global Implementation pull request. I know it have bugs but it can be fixed.

We would appreciate it if you explain to all of us why you don't allow this feature **on purpose** to not be added.
There must be an reason why you **force** manual adding apps into target.txt file.

**Comment by osm0sis** [comment] 2024-08-21 13:32
Duplicate of #48, probably close since they've not accepted your PR.

**Comment by joeyoropesa-dev** [comment] 2024-08-21 17:52
> Duplicate of #48, probably close since they've not accepted your PR.

Yes, it was duplicate to **alert** developer about PR and wanted implementation.

That's why I also included mentions but it seems that dev just ignores them without giving clear reason about ignoring everything related to global feature.

As I said earlier, there must be an logical reason - for example:

Dev doesn't want to have global feature in the module

Or, dev just hates me

I cannot see another reason. The code is "base" for devs - needs fixes but it could work


And probably this is also the **real** reason why dev closed it's source code for this module - to stop this feature coming to future versions of this module.

Right @5ec1cff - there's no reason to hide the truth from people. Just tell directly why you don't want global feature.

**Comment by osm0sis** [comment] 2024-08-21 19:55
They probably just prefer targeted spoofing; less overhead and room for weird interactions.

Anyway, devs can see PRs just as easily as Issues, both trigger notifications/emails.

This is a duplicate issue so you should close it.

**Closed as not planned** 2024-08-21 21:51 UTC
