### ISSUE TITLE
Safetynet does not pass anymore since 1.1.0

### ISSUE THREAD

**Issue by avbfr** [5ec1cff/TrickyStore#55] opened 2024-08-21 16:19 UTC
Hello,

First, Thanks for your work !

I use /e/OS which is an enhanced LineageOS + MicroG custom ROM.

Using 1.0.3, Safetynet pass (Basic) but Key Attestation gets a "Cannot Attest". Gov App cannot be used (In my case, "France identité").

![Screenshot_20240821-091505_Key Attestation](https://github.com/user-attachments/assets/6fabc020-081f-4fb2-b0ab-4640b82e158b)

Using 1.1.0 et 1.1.1 Key attestation pass but Safetynet doesn't anymore (But France identité works !)

Is it possible to restore SafetyNet on the last version ? A few apps are still using it (like Uber for example).

Thanks, 
Best Regards.

**Comment by osm0sis** [comment] 2024-08-21 17:23
Working as intended. You need to use TS with another module like PIFork v10 to spoof a print and pass Play Integrity/SafetyNet. Close this issue.

**Closed as completed** 2024-08-21 19:38 UTC
